import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'
import type { AppSettings, Budget, RecurringExpense, SavingsGoal, Transaction } from '@/types'
import { initializeStorage, saveJSON, userStorageKey } from '@/lib/storage'
import { uid } from '@/lib/utils'
import { loadCloudRecord, saveCloudRecord, type CloudAppData } from '@/lib/cloud'
import { useAuth } from '@/context/AuthContext'

interface AppContextValue { transactions:Transaction[];budgets:Budget[];goals:SavingsGoal[];recurring:RecurringExpense[];settings:AppSettings;ready:boolean;onboardingCompleted:boolean;completeOnboarding:()=>void;addTransaction:(t:Omit<Transaction,'id'>)=>void;updateTransaction:(id:string,p:Partial<Transaction>)=>void;deleteTransaction:(id:string)=>void;addBudget:(b:Omit<Budget,'id'>)=>void;updateBudget:(id:string,p:Partial<Budget>)=>void;deleteBudget:(id:string)=>void;addGoal:(g:Omit<SavingsGoal,'id'|'createdAt'>)=>void;updateGoal:(id:string,p:Partial<SavingsGoal>)=>void;deleteGoal:(id:string)=>void;addToGoal:(id:string,a:number)=>void;addRecurring:(r:Omit<RecurringExpense,'id'>)=>void;updateRecurring:(id:string,p:Partial<RecurringExpense>)=>void;deleteRecurring:(id:string)=>void;updateSettings:(p:Partial<AppSettings>)=>void }
const AppContext=createContext<AppContextValue|null>(null)

export function AppProvider({children}:{children:ReactNode}){
 const {currentUser,session}=useAuth(); const [ready,setReady]=useState(false); const [transactions,setTransactions]=useState<Transaction[]>([]);const [budgets,setBudgets]=useState<Budget[]>([]);const [goals,setGoals]=useState<SavingsGoal[]>([]);const [recurring,setRecurring]=useState<RecurringExpense[]>([]);const [settings,setSettings]=useState<AppSettings>({} as AppSettings);const [onboardingCompleted,setOnboardingCompleted]=useState(false)
 useEffect(()=>{let cancelled=false;(async()=>{if(!currentUser||!session){setReady(false);return}setReady(false);try{const cloud=await loadCloudRecord(session.access_token);if(cancelled)return;if(cloud){const d=cloud.data;setTransactions(d?.transactions??[]);setBudgets(d?.budgets??[]);setGoals(d?.goals??[]);setRecurring(d?.recurring??[]);setSettings(d?.settings??initializeStorage(currentUser.id,currentUser.name).settings);setOnboardingCompleted(Boolean(cloud.onboarding_completed));localStorage.setItem(`moneyCopilot_onboarding_${currentUser.id}`,cloud.onboarding_completed?'true':'false')}else{const local=initializeStorage(currentUser.id,currentUser.name);const migrated:CloudAppData={transactions:local.transactions,budgets:local.budgets,goals:local.goals,recurring:local.recurring,settings:local.settings};const onboarding=Boolean(localStorage.getItem(`moneyCopilot_onboarding_${currentUser.id}`));setTransactions(local.transactions);setBudgets(local.budgets);setGoals(local.goals);setRecurring(local.recurring);setSettings(local.settings);setOnboardingCompleted(onboarding);await saveCloudRecord(currentUser.id,session.access_token,{data:migrated,onboarding_completed:onboarding})}setReady(true)}catch{const local=initializeStorage(currentUser.id,currentUser.name);setTransactions(local.transactions);setBudgets(local.budgets);setGoals(local.goals);setRecurring(local.recurring);setSettings(local.settings);setOnboardingCompleted(Boolean(localStorage.getItem(`moneyCopilot_onboarding_${currentUser.id}`)));setReady(true)}})();return()=>{cancelled=true}},[currentUser?.id,session?.access_token])
 const persist=useCallback((data:CloudAppData)=>{if(!currentUser)return;saveJSON(userStorageKey(currentUser.id),data);if(session)void saveCloudRecord(currentUser.id,session.access_token,{data,onboarding_completed:onboardingCompleted}).catch(()=>{})},[currentUser,session,onboardingCompleted])
 useEffect(()=>{if(ready)persist({transactions,budgets,goals,recurring,settings})},[transactions,budgets,goals,recurring,settings,ready,persist])
 const completeOnboarding=useCallback(()=>{setOnboardingCompleted(true);localStorage.setItem(`moneyCopilot_onboarding_${currentUser?.id}`,'true')},[currentUser?.id])
 useEffect(()=>{if(ready)document.documentElement.classList.toggle('dark',settings.darkMode)},[settings.darkMode,ready])
 const addTransaction=useCallback((t:Omit<Transaction,'id'>)=>setTransactions(p=>[{...t,id:uid('tx')},...p]),[]);const updateTransaction=useCallback((id:string,p:Partial<Transaction>)=>setTransactions(p0=>p0.map(t=>t.id===id?{...t,...p}:t)),[]);const deleteTransaction=useCallback((id:string)=>setTransactions(p=>p.filter(t=>t.id!==id)),[]);const addBudget=useCallback((b:Omit<Budget,'id'>)=>setBudgets(p=>[...p,{...b,id:uid('budget')}]),[]);const updateBudget=useCallback((id:string,p:Partial<Budget>)=>setBudgets(p0=>p0.map(b=>b.id===id?{...b,...p}:b)),[]);const deleteBudget=useCallback((id:string)=>setBudgets(p=>p.filter(b=>b.id!==id)),[]);const addGoal=useCallback((g:Omit<SavingsGoal,'id'|'createdAt'>)=>setGoals(p=>[...p,{...g,id:uid('goal'),createdAt:new Date().toISOString()}]),[]);const updateGoal=useCallback((id:string,p:Partial<SavingsGoal>)=>setGoals(p0=>p0.map(g=>g.id===id?{...g,...p}:g)),[]);const deleteGoal=useCallback((id:string)=>setGoals(p=>p.filter(g=>g.id!==id)),[]);const addToGoal=useCallback((id:string,a:number)=>setGoals(p=>p.map(g=>g.id===id?{...g,saved:Math.min(g.target,g.saved+a)}:g)),[]);const addRecurring=useCallback((r:Omit<RecurringExpense,'id'>)=>setRecurring(p=>[...p,{...r,id:uid('rec')}]),[]);const updateRecurring=useCallback((id:string,p:Partial<RecurringExpense>)=>setRecurring(p0=>p0.map(r=>r.id===id?{...r,...p}:r)),[]);const deleteRecurring=useCallback((id:string)=>setRecurring(p=>p.filter(r=>r.id!==id)),[]);const updateSettings=useCallback((p:Partial<AppSettings>)=>setSettings(prev=>({...prev,...p,studentMode:p.studentMode?{...prev.studentMode,...p.studentMode}:prev.studentMode})),[])
 const value=useMemo(()=>({transactions,budgets,goals,recurring,settings,ready,onboardingCompleted,completeOnboarding,addTransaction,updateTransaction,deleteTransaction,addBudget,updateBudget,deleteBudget,addGoal,updateGoal,deleteGoal,addToGoal,addRecurring,updateRecurring,deleteRecurring,updateSettings}),[transactions,budgets,goals,recurring,settings,ready,onboardingCompleted,completeOnboarding,addTransaction,updateTransaction,deleteTransaction,addBudget,updateBudget,deleteBudget,addGoal,updateGoal,deleteGoal,addToGoal,addRecurring,updateRecurring,deleteRecurring,updateSettings])
 return <AppContext.Provider value={value}>{children}</AppContext.Provider>
}
export function useApp(){const ctx=useContext(AppContext);if(!ctx)throw new Error('useApp must be used within AppProvider');return ctx}
